// Code generated by github.com/luyunbo/protoc-gen-gin. DO NOT EDIT.

package proto

import (
	context "context"
	errors "errors"
	gin "github.com/gin-gonic/gin"
	metadata "google.golang.org/grpc/metadata"
	"google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the luyunbo/protoc-gen-gin package it is being compiled against.
// context.metadata.
//gin.errors.

type UserHTTPServer interface {
	CheckPassword(context.Context, *CheckPasswordInfo) (*CheckResult, error)

	CreateUser(context.Context, *CreateUserInfo) (*UserInfo, error)

	GetUserById(context.Context, *IdReq) (*UserInfo, error)

	GetUserByMobile(context.Context, *MobileReq) (*UserInfo, error)

	GetUserListInfo(context.Context, *PackageReq) (*UserListInfo, error)

	UpdateUser(context.Context, *UpdateUserInfo) (*emptypb.Empty, error)
}

func RegisterUserHTTPServer(r gin.IRouter, srv UserHTTPServer) {
	s := User{
		server: srv,
		router: r,
		resp:   defaultUserResp{},
	}
	s.RegisterService()
}

type User struct {
	server UserHTTPServer
	router gin.IRouter
	resp   interface {
		Error(ctx *gin.Context, err error)
		ParamsError(ctx *gin.Context, err error)
		Success(ctx *gin.Context, data interface{})
	}
}

// Resp 返回值
type defaultUserResp struct{}

func (resp defaultUserResp) response(ctx *gin.Context, status, code int, msg string, data interface{}) {
	ctx.JSON(status, map[string]interface{}{
		"code": code,
		"msg":  msg,
		"data": data,
	})
}

// Error 返回错误信息
func (resp defaultUserResp) Error(ctx *gin.Context, err error) {
	code := -1
	status := 500
	msg := "UNKNOWN"

	if err == nil {
		msg += ", err is nil"
		resp.response(ctx, status, code, msg, nil)
		return
	}

	type iCode interface {
		HTTPCode() int
		Message() string
		Code() int
	}

	var c iCode
	if errors.As(err, &c) {
		status = c.HTTPCode()
		code = c.Code()
		msg = c.Message()
	}

	_ = ctx.Error(err)

	resp.response(ctx, status, code, msg, nil)
}

// ParamsError 参数错误
func (resp defaultUserResp) ParamsError(ctx *gin.Context, err error) {
	_ = ctx.Error(err)
	resp.response(ctx, 400, 400, "INVALID_ARGUMENT", nil)
}

// Success 返回成功信息
func (resp defaultUserResp) Success(ctx *gin.Context, data interface{}) {
	resp.response(ctx, 200, 0, "ok", data)
}

func (s *User) GetUserListInfo_0(ctx *gin.Context) {
	var in PackageReq

	if err := ctx.ShouldBindQuery(&in); err != nil {
		s.resp.ParamsError(ctx, err)
		return
	}

	md := metadata.New(nil)
	for k, v := range ctx.Request.Header {
		md.Set(k, v...)
	}
	newCtx := metadata.NewIncomingContext(ctx, md)
	out, err := s.server.(UserHTTPServer).GetUserListInfo(newCtx, &in)
	if err != nil {
		s.resp.Error(ctx, err)
		return
	}

	s.resp.Success(ctx, out)
}

func (s *User) GetUserByMobile_0(ctx *gin.Context) {
	var in MobileReq

	if err := ctx.ShouldBindJSON(&in); err != nil {
		s.resp.ParamsError(ctx, err)
		return
	}

	md := metadata.New(nil)
	for k, v := range ctx.Request.Header {
		md.Set(k, v...)
	}
	newCtx := metadata.NewIncomingContext(ctx, md)
	out, err := s.server.(UserHTTPServer).GetUserByMobile(newCtx, &in)
	if err != nil {
		s.resp.Error(ctx, err)
		return
	}

	s.resp.Success(ctx, out)
}

func (s *User) GetUserById_0(ctx *gin.Context) {
	var in IdReq

	if err := ctx.ShouldBindJSON(&in); err != nil {
		s.resp.ParamsError(ctx, err)
		return
	}

	md := metadata.New(nil)
	for k, v := range ctx.Request.Header {
		md.Set(k, v...)
	}
	newCtx := metadata.NewIncomingContext(ctx, md)
	out, err := s.server.(UserHTTPServer).GetUserById(newCtx, &in)
	if err != nil {
		s.resp.Error(ctx, err)
		return
	}

	s.resp.Success(ctx, out)
}

func (s *User) CreateUser_0(ctx *gin.Context) {
	var in CreateUserInfo

	if err := ctx.ShouldBindJSON(&in); err != nil {
		s.resp.ParamsError(ctx, err)
		return
	}

	md := metadata.New(nil)
	for k, v := range ctx.Request.Header {
		md.Set(k, v...)
	}
	newCtx := metadata.NewIncomingContext(ctx, md)
	out, err := s.server.(UserHTTPServer).CreateUser(newCtx, &in)
	if err != nil {
		s.resp.Error(ctx, err)
		return
	}

	s.resp.Success(ctx, out)
}

func (s *User) UpdateUser_0(ctx *gin.Context) {
	var in UpdateUserInfo

	if err := ctx.ShouldBindJSON(&in); err != nil {
		s.resp.ParamsError(ctx, err)
		return
	}

	md := metadata.New(nil)
	for k, v := range ctx.Request.Header {
		md.Set(k, v...)
	}
	newCtx := metadata.NewIncomingContext(ctx, md)
	out, err := s.server.(UserHTTPServer).UpdateUser(newCtx, &in)
	if err != nil {
		s.resp.Error(ctx, err)
		return
	}

	s.resp.Success(ctx, out)
}

func (s *User) CheckPassword_0(ctx *gin.Context) {
	var in CheckPasswordInfo

	if err := ctx.ShouldBindJSON(&in); err != nil {
		s.resp.ParamsError(ctx, err)
		return
	}

	md := metadata.New(nil)
	for k, v := range ctx.Request.Header {
		md.Set(k, v...)
	}
	newCtx := metadata.NewIncomingContext(ctx, md)
	out, err := s.server.(UserHTTPServer).CheckPassword(newCtx, &in)
	if err != nil {
		s.resp.Error(ctx, err)
		return
	}

	s.resp.Success(ctx, out)
}

func (s *User) RegisterService() {

	s.router.Handle("GET", "/v1/users", s.GetUserListInfo_0)

	s.router.Handle("POST", "/v1/users/mobile", s.GetUserByMobile_0)

	s.router.Handle("POST", "/v1/users/id", s.GetUserById_0)

	s.router.Handle("POST", "/v1/users/create", s.CreateUser_0)

	s.router.Handle("POST", "/v1/users/update", s.UpdateUser_0)

	s.router.Handle("POST", "/v1/users/password", s.CheckPassword_0)

}
